### ISSUE TITLE
"XMLHttpRequestBodyInit" and "VRFrameData" errors

### ISSUE THREAD

**Issue by punkoffice** [BabylonJS/BabylonToolkit#39]
I'm using Unity 2021.2.1f1 and Babylon Toolkit:  V5.0.0-A48.3X9

I get this error message when trying to compile the script:

Assets/[Babylon]/Template/Typings/babylon.d.ts(566,32): error TS2304: Cannot find name 'XMLHttpRequestBodyInit'.
Assets/[Babylon]/Template/Typings/babylon.d.ts(90425,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'VRFrameData' must be of type '{ new (): VRFrameData; prototype: VRFrameData; }', but here has type 'any'.

How do I get around this?

**Comment by MackeyK24** [comment]
This is because the latest babylon js has updated to typescript 4.4.2

INstall at least that version

To install latest global:
npm install -g typescript

I also now support local type script compilers per project... ion cause you
cant or dont want to change your globally installed typescript version to
stay compatable with older projects...

Anyways check the Script Compiler Section of the Toolkit Exporter Panel
to install typescript to your local project... from the root of your
toolkit project (with the package.json), run:
npm install

Then Rebuild Project Editor to see changes in the Script Compiler Section

**Comment by punkoffice** [comment]
Got it!  It all works now, thanks mate
