### ISSUE TITLE
Unity Exporter; Wrong direction of babylon's  `Spot light` 

### ISSUE THREAD

**Issue by Troxid** [BabylonJS/BabylonToolkit#6]
**Exporter**: Unity - Version 4.0.0 - Alpha 10
 
When `Spot light` is used in the parent and its parent get transform - an exported direction is wrong.

Unity scene and right light direction (pink arrows): 
![capture1](https://user-images.githubusercontent.com/3336378/51803262-3010eb80-2264-11e9-9522-7e7266a609f6.PNG)

Exported scene:
![capture2](https://user-images.githubusercontent.com/3336378/51803281-6189b700-2264-11e9-8ab4-129034da0220.PNG)

I think problem is in `Babylon/Sources/SceneBuilder.Light.cs`
``` C#
var direction = new Vector3(0, 0, 1);
var transformedDirection = light.transform.TransformDirection(direction);
babylonLight.direction = transformedDirection.ToFloat();
```
I changed it to:
``` C#
var direction = light.transform.forward;
var transformedDirection = light.transform.InverseTransformDirection(direction);            
babylonLight.direction = transformedDirection.ToFloat();
```
and it seems to be working fine:

![capture3](https://user-images.githubusercontent.com/3336378/51803605-24272880-2268-11e9-8323-b0e2c07ac0a1.PNG)

I can't check it for 100%, because the `Inspector` doesn't show me the orientation of light.

**Comment by MackeyK24** [comment]
Well, for now, folks that are still gonna use the old version. This one can be fixed by using @Troxid fixes above. 

New toolkit is GLTF 2.0 spec now

Light can camera transforms are exported differently (GLTF 2.0 spec) now and does NOT use light.transform.TransformDirection or the Inverse for exported the light component that is attached to a node. They are exported as component on a node where the node itself has the transform. The light or camera is just a child rig wither point Babylon.Forward for left and systems and BABYLON.Backwards() for right handed system.
