### ISSUE TITLE
Animation problem Unity exporter 

### ISSUE THREAD

**Issue by vanlecs09** [BabylonJS/BabylonToolkit#7]
![fish3d](https://user-images.githubusercontent.com/17665525/48936195-be06e800-ef3c-11e8-937e-d2092f7ea762.gif)

The animation of my gameobject is weird after doing build and preview

**Comment by vanlecs09** [comment]
I add babylon animation component to object. I think the problem come from curve animation?

**Comment by vanlecs09** [comment]
<img width="185" alt="screen shot 2018-11-28 at 4 19 13 pm" src="https://user-images.githubusercontent.com/17665525/49141537-69db7980-f329-11e8-8ba3-0bbe61712037.png">
<img width="225" alt="screen shot 2018-11-28 at 4 20 14 pm" src="https://user-images.githubusercontent.com/17665525/49141589-85df1b00-f329-11e8-997e-a8c6518cc56c.png">

Hi @sebavan 
Uncheck "Alpha is transparent" solve problem, but the fish lose its caustic effect. I don't see caustic texture in browser sources. Can you explain how shader update texture if they are not include in model?

<img width="101" alt="screen shot 2018-11-28 at 4 23 25 pm" src="https://user-images.githubusercontent.com/17665525/49141763-f423dd80-f329-11e8-8685-a33ba3a2cd81.png">

**Comment by MackeyK24** [comment]
I dont think this is the right package. It has a bunch of random letter
folder. Does not look like actual scene package.

Use Unity to package your scene:
https://docs.unity3d.com/Manual/HOWTO-exportpackage.html

**Comment by MackeyK24** [comment]
This is because this animation is a Unity animation that has BOTH transform animation on the object its self as well as skeletal animations. The old toolkit was kind oif an EITHER OR thing. Either its doing transform animation on the mesh position rotation and scale OR its doing BONE translation animation.

The GLTF 2.0 spec (Which i wrote code to support all animation export types) supports 
- Transform Animations
- Skeletal Animations
- Blend Shape Animations
- Multi Target Animations (Both Transform and Skeletal Animation In Same Animation File)

This is fixed with new toolkit that uses GLTF Animation Export spec... So all works great now with multiple targets of the mesh :)
