### ISSUE TITLE
Problem when exporting textures from Unity

### ISSUE THREAD

**Issue by jeremy219** [BabylonJS/BabylonToolkit#8]
Hello there,

So I have been using the unity exporter to babylon since this monday and this is working super fine, thank you for this amazing tool!

Except.. I have a texture issue. 

![screen1](https://user-images.githubusercontent.com/28017558/55066729-a1132a80-507e-11e9-9ae7-e7924a15209f.JPG)

So this is pretty much how this is supposed to look like (or kindof)

But this is what I get as an output :

![screen2](https://user-images.githubusercontent.com/28017558/55066859-f2bbb500-507e-11e9-902e-99c8ab46ad18.JPG)

Do you guys have any idea, did I do something wrong ? :(

Thank you very much in advance!

**Comment by MackeyK24** [comment]
Can you please package up the scene as a .unitypackage and send to me. I will check it out :)

**Comment by jeremy219** [comment]
Thank you Mackey!

Here it is : 

https://www.dropbox.com/s/skm9g1dxadl26x8/exportedPackage.unitypackage?dl=0

Tell me if you have any issue.

I have a warning concerning the skybox that I use in the scene, I have tried different ones but I'm not sure that this is where the problem comes from.

**Comment by MackeyK24** [comment]
Your sky box was not in the package.. Send me your skybox image(s)...

What type of skybox are you trying to use ??

Six Sided JPG/PNG

or 

HDR/EXR

or what ???

**Comment by jeremy219** [comment]
At first I was using a procedural Skybox but assuming it gave me the error "Unsupported skybox type" I thought that maybe this was the cause of the texture issue.

But actually I don't really care about the skybox and lightings for now, you can even remove it, i just want my models to be exported with the right materials :(

Is it necessary to have a skybox for that purpose?

**Comment by MackeyK24** [comment]
No... Is not needed.. BTW Procedural Skyboxes Not Support... Use a Six-Sided Skybox Instead.

Is very complex setup with still alot of UNITY stuff that will not be exported... Like all your reflection probes

But i will see what can be done... If anything with the current version of toolkit.

**Comment by MackeyK24** [comment]
Yo @jeremy219 ... Sorry bro... There are issues in the current version of the toolkit that ARE now fixed in the upcoming toolkit. But there is not much i can do about your scene in the current toolkit. WAY TOO WORK to go back and REDO how i generate meshes with all its positions, normals, tangents, uvs, vertex colors and of course triangle indices... Plus the picture perfect PBR export pipeline i created for the new GLTF based Babylon Toolkit.

So its a Good News, Bad News kinda thing...

The bad news, the current version cant handle your scene as is. So you have to wait for the new toolkit.  Good New... It looks pretty freaking sweet in the new toolkit:

I moved this issue to babylon forums: https://forum.babylonjs.com/t/toolkit-texture-exporter-problems/2200

Here is new Babylon Toolkit (with your workshop scene):

![Screen Shot 2019-03-27 at 10 30 36 PM](https://user-images.githubusercontent.com/5013415/55142979-e3ba1e80-50e1-11e9-86fa-9908bb39a416.png)

And new Babylon Toolkit Exported Scene:

![Screen Shot 2019-03-27 at 10 30 55 PM](https://user-images.githubusercontent.com/5013415/55143011-f2083a80-50e1-11e9-94dc-11bded6ba26f.png)

NOTE: There is still an issue i am having with SPOT LIGHTS so the the construction props light is not on... But everything else looks pretty freaking good for a ZERO code re-creation of a unity scene in pure BabylonJS with GLTF Unity Meta Data :)
